### ISSUE TITLE
request: add a flag to display Length header or not.

### ISSUE THREAD

**Issue by dan-da** [wolandr/pretty-hex#4]
Sometimes it can be desirable to dump pure hex contents without "Length" header line.    Any chance we can get a flag for this?

**Comment by wolandr** [comment]
New version v0.2 implements style configuration, now you could try `title: false` in `HexConfig`. See more details in [docs](https://docs.rs/pretty-hex/0.2.0/pretty_hex/#example-of-config_hex), and feel free to report issues and contribute.
